### ISSUE TITLE
Multi-Argument Ref() constructor concats terms in JS

### ISSUE THREAD

**Issue by eaceaser** [faunadb/faunadb-js#106]
You can't express the construction of a `Ref` with a fauna-generated ID, because JS will try to concat the terms in code.

So, for example, saying `q.Ref("classes/some_class", q.NextId())` will send a ref to the DB of `"classes/some_class/[object]"` or something where `[object]` is the stringification of the `q.NextId()` object.

**Comment by eaceaser** [comment]
nevermind, this is sort of my fault. The `q.Ref` FUNCTION is what I want.

**Comment by eaceaser** [comment]
Nevermind, this actually is broken.

**Comment by erickpintor** [comment]
Issue moved to [faunadb/sales-engineering #486](https://github.com/faunadb/sales-engineering/issues/486) via [**ZenHub**](https://www.zenhub.com/)
