### ISSUE TITLE
Don't let superagent automatically parse JSON

### ISSUE THREAD

**Issue by andy-faunadb** [faunadb/faunadb-js#64]
According to http://visionmedia.github.io/superagent/ (section: "Parsing response bodies"), superagent will automatically parse JSON and expose as `response.body`.
If true, this is bad behavior because we parse JSON ourselves (and do conversions).
This may also affect behavior is bad JSON is returned. We want any exceptions to be ours, not superagent's.

**Comment by erickpintor** [comment]
Not necessary anymore after the last driver review.
