### ISSUE TITLE
Way to send floats that happen to equal ints

### ISSUE THREAD

**Issue by andy-faunadb** [faunadb/faunadb-js#67]
`JSON.stringify(2.0)` is "2". In the chance that a number divisible by 1 still ought to be represented as a float within FaunaDB, we need a way to indicate that.

**Comment by erickpintor** [comment]
Issue moved to [faunadb/sales-engineering #401](https://github.com/faunadb/sales-engineering/issues/401) via [**ZenHub**](https://www.zenhub.com/)
